export let productsData = [{
   photo: "african-style-chairs.jpg",
   title: "High-Back Bench",
   price: "10.99",
   company: "Ikea",
   quantity: "1",
},
{
   photo: "white-bend-chair.jpg",
   title: "White bend-chair",
   price: "12.99",
   company: "Liddy",
   quantity: "1",
},
{
   photo: "black-sofa.jpg",
   title: "Black sofa",
   price: "94.99",
   company: "Marcos",
   quantity: "1",
},
{
   photo: "royal-bed.jpg",
   title: "Royal bed",
   price: "79.99",
   company: "Caressa",
   quantity: "1",
},
{
   photo: "wooden-bookshelf.jpg",
   title: "Wooden bookshelf",
   price: "25.99",
   company: "Ikea",
   quantity: "1",
},
{
   photo: "white-swing-chair.jpg",
   title: "White swing-chair",
   price: "17.99",
   company: "Marcos",
   quantity: "1",
},
{
   photo: "hard-bed.jpg",
   title: "Hard bed",
   price: "82.99",
   company: "Ikea",
   quantity: "1",
},
{
   photo: "gray-chairs.jpg",
   title: "Gray chairs",
   price: "17.99",
   company: "Liddy",
   quantity: "1",
},
{
   photo: "white-sofa.jpg",
   title: "White sofa",
   price: "59.99",
   company: "Ikea",
   quantity: "1",
},
{
   photo: "orange-sofa.jpg",
   title: "Orange sofa",
   price: "51.99",
   company: "Marcos",
   quantity: "1",
},
{
   photo: "multibox-shelf.jpg",
   title: "Multibox shelf",
   price: "35.99",
   company: "Caressa",
   quantity: "1",
},
{
   photo: "soft-bed.jpg",
   title: "Soft bed",
   price: "85.99",
   company: "Ikea",
   quantity: "1",
},
{
   photo: "black-bed.jpg",
   title: "Black bed",
   price: "69.99",
   company: "Liddy",
   quantity: "1",
}]